"""Build and send the hiring digest email.

Delivery uses stdlib smtplib so there are zero extra dependencies and it works
with any SMTP provider (Gmail app password, SES SMTP, Postmark, Mailgun, etc.).
Set SMTP_HOST/PORT/USER/PASS and EMAIL_FROM/EMAIL_TO. To swap to a transactional
API (Resend/SendGrid/SES) instead, replace send_email() only.
"""
from __future__ import annotations

import html
import smtplib
from email.message import EmailMessage
from typing import Any

from .config import config


def tweet_url(rec: dict[str, Any]) -> str:
    author = rec.get("author") or {}
    username = author.get("username") or "i"
    return f"https://x.com/{username}/status/{rec['id']}"


def _row(rec: dict[str, Any]) -> str:
    author = rec.get("author") or {}
    name = html.escape(author.get("name") or "")
    handle = author.get("username")
    handle_html = (
        f'<a href="https://x.com/{html.escape(handle)}">@{html.escape(handle)}</a>'
        if handle else ""
    )

    role = html.escape(rec.get("role") or "")
    company = html.escape(rec.get("company") or "")
    location = html.escape(rec.get("location") or "")
    seniority = html.escape(rec.get("seniority") or "")
    summary = html.escape(rec.get("summary") or "")
    apply_url = rec.get("apply_url")

    title_bits = " · ".join(b for b in (role, company) if b) or "Hiring post"
    meta_bits = " · ".join(b for b in (seniority, location) if b)

    apply_html = (
        f' &nbsp;·&nbsp; <a href="{html.escape(apply_url)}">Apply / details</a>'
        if apply_url else ""
    )

    return f"""
    <div style="margin:0 0 18px;padding:0 0 18px;border-bottom:1px solid #eee;">
      <div style="font-size:15px;font-weight:600;color:#111;">{title_bits}</div>
      {f'<div style="font-size:13px;color:#666;margin-top:2px;">{meta_bits}</div>' if meta_bits else ''}
      {f'<div style="font-size:14px;color:#333;margin-top:6px;">{summary}</div>' if summary else ''}
      <div style="font-size:12px;color:#888;margin-top:6px;">
        {name} {handle_html} &nbsp;·&nbsp;
        <a href="{tweet_url(rec)}">View tweet</a>{apply_html}
      </div>
    </div>"""


def build_html(records: list[dict[str, Any]]) -> str:
    rows = "".join(_row(r) for r in records)
    return f"""<!doctype html><html><body style="margin:0;background:#f6f6f6;">
      <div style="max-width:640px;margin:0 auto;padding:24px;font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;background:#fff;">
        <h1 style="font-size:18px;color:#111;margin:0 0 4px;">Hiring digest</h1>
        <div style="font-size:13px;color:#888;margin:0 0 20px;">
          {len(records)} new hiring post{'s' if len(records) != 1 else ''} from your timeline
        </div>
        {rows}
        <div style="font-size:11px;color:#aaa;margin-top:16px;">
          Generated by twitter-scrapper · classified with Claude
        </div>
      </div>
    </body></html>"""


def build_text(records: list[dict[str, Any]]) -> str:
    lines = [f"Hiring digest — {len(records)} new post(s)", ""]
    for r in records:
        title = " · ".join(b for b in (r.get("role"), r.get("company")) if b) or "Hiring post"
        lines.append(f"- {title}")
        if r.get("summary"):
            lines.append(f"  {r['summary']}")
        lines.append(f"  {tweet_url(r)}")
        if r.get("apply_url"):
            lines.append(f"  apply: {r['apply_url']}")
        lines.append("")
    return "\n".join(lines)


def send_email(subject: str, html_body: str, text_body: str) -> None:
    if not (config.smtp_host and config.email_from and config.email_to):
        raise RuntimeError(
            "Email not configured: set SMTP_HOST, EMAIL_FROM and EMAIL_TO."
        )

    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = config.email_from
    msg["To"] = config.email_to
    msg.set_content(text_body)
    msg.add_alternative(html_body, subtype="html")

    with smtplib.SMTP(config.smtp_host, config.smtp_port, timeout=30) as server:
        if config.smtp_starttls:
            server.starttls()
        if config.smtp_user:
            server.login(config.smtp_user, config.smtp_pass)
        server.send_message(msg)
